"""Content-focused Persian word-cloud helpers.

The stopword collection intentionally lives in this small, isolated module.
An administrator or developer can extend ``PERSIAN_STOPWORDS`` without
touching the dashboard aggregation query or any presentation code.
"""

from __future__ import annotations

import re
from collections import Counter


# Keep this collection in one place so it is easy to expand for a newsroom's
# own recurring, low-information vocabulary.  Both normal and half-space
# variants are compared by ``_comparison_form`` below.
PERSIAN_STOPWORDS = frozenset(
    {
        # حرف اضافه، ربط و واژه‌های ساختاری
        "از", "به", "در", "با", "برای", "که", "و", "یا", "اما", "اگر", "نیز",
        "تا", "بر", "درباره", "را", "هم", "ضمن", "پس", "قبل", "بعد", "روی",
        "زیرا", "ولی", "بلکه", "چون", "همچنین", "هرچند", "بنابراین", "یک", "دو",
        "سه", "های", "هایی", "استفاده",
        # ضمیر، اشاره و واژه‌های ارجاعی
        "من", "ما", "او", "وی", "آنها", "این", "آن", "خود", "هر", "ایشان",
        "شما", "تو", "آنها", "آنان", "همه", "هیچ", "چیزی", "کسی",
        # فعل‌ها و ترکیب‌های خبریِ عمومی
        "است", "هست", "بود", "شد", "شود", "شده", "داشت", "دارد", "دارند",
        "داشتند", "کرد", "کرده", "کردند", "می", "نمی", "باید", "خواهد", "خواهند",
        "کنید", "کن", "شدن", "گفتند", "گویند", "میشود", "نمیشود", "میکند",
        "نمیکند", "میکنند", "نمیکنند", "داشتن", "بودن", "است", "هستند",
        "نیست", "کند", "شود", "شوند", "کردن", "میگردد", "نگردد",
        # عبارت‌های خبری با ارزش تمایزبخشی کم
        "گفت", "افزود", "اعلام", "اظهار", "خبر", "گزارش", "رسانه", "خبرگزاری",
        "عنوان", "کردند", "شدند", "شدهاند", "منتشر", "مطابق", "براساس", "بررسی",
        "امروز", "روز", "شب", "سال", "ماه", "باره", "مورد", "علیه", "دیگر",
        "منبع", "قرار", "نسبت", "تمام", "بسیار",
    }
)

# Weights are deliberately visible and easy to tune.  Tags generated by the
# analysis pipeline carry more editorial meaning than a raw message body.
WORD_CLOUD_WEIGHTS = {
    "message": 1,
    "analysis_subject": 2,
    "event_title": 2,
    "general_topic": 4,
    "specific_topic": 5,
    "speaker": 5,
}

_ZWNJ = "\u200c"
_URL_RE = re.compile(
    r"(?:(?:https?|ftp)://|www\.)[^\s<>]+|(?:t\.me|ble\.ir|web\.bale\.ai)/[^\s<>]+",
    flags=re.IGNORECASE,
)
_DIACRITICS_RE = re.compile(r"[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed]")
_DIGITS_RE = re.compile(r"[0-9\u0660-\u0669\u06f0-\u06f9]")
_NON_PERSIAN_LETTER_RE = re.compile(r"[^\u0621-\u063a\u0641-\u06cc\u067e\u0686\u0698\u06a9\u06af\u200c\s]")
_TOKEN_RE = re.compile(r"[آ-ی](?:[آ-ی\u200c]*[آ-ی])?")
_EDGE_ZWNJ_RE = re.compile(r"(?<![آ-ی])\u200c|\u200c(?![آ-ی])")
_PERSIAN_TRANSLATION = str.maketrans(
    {
        "ي": "ی",
        "ى": "ی",
        "ئ": "ی",
        "ك": "ک",
        "ة": "ه",
        "ۀ": "ه",
        "ؤ": "و",
    }
)
_COMPACT_STOPWORDS = frozenset(word.replace(_ZWNJ, "") for word in PERSIAN_STOPWORDS)


def normalize_for_wordcloud(value: object) -> str:
    """Return plain Persian text suitable for content-word extraction.

    ZWNJ is retained *inside* a word.  This means ``نمی‌شود`` stays one token
    long enough to be recognised as a generic verb phrase and is not turned
    into arbitrary fragments such as ``نمی`` and ``شود``.
    """

    text = _URL_RE.sub(" ", str(value or ""))
    text = text.translate(_PERSIAN_TRANSLATION)
    text = _DIACRITICS_RE.sub("", text).replace("ـ", "")
    text = _DIGITS_RE.sub(" ", text)
    # This drops punctuation, Latin text and emoji while retaining Persian
    # letters and a meaningful half-space in the middle of a word.
    text = _NON_PERSIAN_LETTER_RE.sub(" ", text)
    text = re.sub(f"{_ZWNJ}{{2,}}", _ZWNJ, text)
    text = _EDGE_ZWNJ_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


def _comparison_form(word: str) -> str:
    return word.replace(_ZWNJ, "")


def is_content_word(word: str) -> bool:
    """Whether a normalized token has enough editorial value to be counted."""

    compact = _comparison_form(word)
    if len(compact) < 3:
        return False
    if word in PERSIAN_STOPWORDS or compact in _COMPACT_STOPWORDS:
        return False
    # Retain half-spaces in the normalizer but drop habitual verb constructions
    # such as «می‌شود» and «نمی‌توان» as a whole, rather than splitting them.
    if word.startswith((f"می{_ZWNJ}", f"نمی{_ZWNJ}")):
        return False
    return True


def content_words(value: object) -> list[str]:
    """Extract normalized, non-stopword Persian content words from a value."""

    return [
        token
        for token in _TOKEN_RE.findall(normalize_for_wordcloud(value).lower())
        if is_content_word(token)
    ]


def add_weighted_words(
    counter: Counter[str], value: object, weight: int | float = 1
) -> None:
    """Add content words from ``value`` using a positive editorial weight."""

    safe_weight = max(0, int(weight or 0))
    if not safe_weight:
        return
    for word in content_words(value):
        counter[word] += safe_weight


def ranked_word_cloud(counter: Counter[str], limit: int = 42) -> list[dict[str, int | str]]:
    """Return a deterministic, frequency-first payload for the UI layout."""

    return [
        {"word": word, "count": int(count)}
        for word, count in sorted(counter.items(), key=lambda item: (-item[1], item[0]))[:limit]
    ]
